(source-directories (cons "core" (source-directories)))

(load "core/base/prelude.ss")
(load "core/blocks/block.ss")
(load "core/base/sha256.ss")
(load "boundary/io/fs.ss")

(doc 'module 'store-api)
(doc 'description "Persistent Block Storage API for The Fold")
(doc 'layer 'boundary)
(doc 'purity 'partial)
(doc 'dependencies '(core/base/prelude core/blocks/block core/base/sha256 boundary/io/fs))

(doc 'note "A clean, functional API for storing and retrieving blocks from the content-addressed .store filesystem")

(doc 'design-principles "
  • Pure functional interface (except fs-capability mutation)
  • Content-addressed (blocks identified by hash)
  • Composable (works with existing block primitives)
  • Efficient (leverage existing fs.ss operations)")

(doc 'tier-assignment "
  Tier 3-4: Most operations (disk I/O, minimal computation)
  Tier 5-6: Filtering and searching operations")

(doc 'section 'core-storage-operations)

(define (store-put! fs block)
  (doc 'type (-> FSCap Block Hash))
  (doc 'description "Store a block and return its hash")
  (doc 'note "Pure operation: identical blocks always produce same hash")
  (doc 'tier '(3 4))
  (doc 'export #t)
  (let ([h (hash-block block)])
       (fs-store! fs block)
       h))

(define (store-get fs hash)
  (doc 'type (-> FSCap Hash (Maybe Block)))
  (doc 'description "Retrieve a block by hash, or #f if not found")
  (doc 'tier '(3 4))
  (doc 'export #t)
  (fs-fetch fs hash))

(define (store-exists? fs hash)
  (doc 'type (-> FSCap Hash Boolean))
  (doc 'description "Check if a block exists in the store")
  (doc 'tier '(3 4))
  (doc 'export #t)
  (not (eq? (fs-fetch fs hash) #f)))

(define (store-all-hashes fs)
  (doc 'type (-> FSCap (List Hash)))
  (doc 'description "Get all hashes in the store")
  (doc 'tier '(3 4))
  (doc 'export #t)
  (fs-all-hashes fs))

(define (store-count fs)
  (doc 'type (-> FSCap Integer))
  (doc 'description "Count total blocks in store")
  (doc 'tier '(3 4))
  (doc 'export #t)
  (length (fs-all-hashes fs)))

(doc 'section 'filtering-and-querying)

(define (store-all-blocks fs)
  (doc 'type (-> FSCap (List Block)))
  (doc 'description "Load all blocks from store")
  (doc 'warning "Loads everything into memory. Use with care on large stores")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (map (lambda (h) (fs-fetch fs h))
       (fs-all-hashes fs)))

(define (store-filter fs predicate)
  (doc 'type (-> FSCap (-> Block Boolean) (List Block)))
  (doc 'description "Find all blocks matching predicate")
  (doc 'note "Loads blocks lazily during iteration")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (filter predicate (store-all-blocks fs)))

(define (store-find-by-tag fs tag)
  (doc 'type (-> FSCap Symbol (List Block)))
  (doc 'description "Find all blocks with given tag")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (store-filter fs (lambda (b) (eq? (block-tag b) tag))))

(define (store-find-by-payload fs predicate)
  (doc 'type (-> FSCap (-> Bytevector Boolean) (List Block)))
  (doc 'description "Find all blocks where payload matches predicate")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (store-filter fs (lambda (b) (predicate (block-payload b)))))

(define (store-find-by-payload-contains fs substring)
  (doc 'type (-> FSCap String (List Block)))
  (doc 'description "Find all blocks whose payload (as UTF-8 string) contains substring")
  (doc 'note "Guards against invalid UTF-8 in binary payloads")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (store-filter fs (lambda (b)
                           (guard (e [else #f])
                                  (let ([payload-str (utf8->string (block-payload b))])
                                       (string-contains? payload-str substring))))))

(define (store-find-by-ref fs target-hash)
  (doc 'type (-> FSCap Hash (List Block)))
  (doc 'description "Find all blocks that reference given hash")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (store-filter fs (lambda (b)
                           (let ([refs (block-refs b)])
                                (let check-refs ([i 0])
                                     (cond
                                      [(>= i (vector-length refs)) #f]
                                      [(equal? (vector-ref refs i) target-hash) #t]
                                      [else (check-refs (+ i 1))]))))))

(doc 'section 'batch-operations)

(define (store-put-many! fs blocks)
  (doc 'type (-> FSCap (List Block) (List Hash)))
  (doc 'description "Store multiple blocks and return their hashes")
  (doc 'tier '(4 5))
  (doc 'export #t)
  (map (lambda (b) (store-put! fs b)) blocks))

(define (store-get-many fs hashes)
  (doc 'type (-> FSCap (List Hash) (List (Maybe Block))))
  (doc 'description "Retrieve multiple blocks by hash")
  (doc 'tier '(4 5))
  (doc 'export #t)
  (map (lambda (h) (store-get fs h)) hashes))

(doc 'section 'statistics-and-inspection)

(define (store-stats fs)
  (doc 'type (-> FSCap Alist))
  (doc 'description "Compute statistics about the store")
  (doc 'returns "((total . N) (by-tag . ((tag . count) ...)) (total-bytes . N))")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (let* ([all-blocks (store-all-blocks fs)]
         [total (length all-blocks)]
         [total-bytes (fold-left (lambda (acc b)
                                         (+ acc (bytevector-length (block-payload b))))
                                 0
                                 all-blocks)]
         [by-tag (count-by-tag all-blocks)])
        `((total . ,total)
          (by-tag . ,by-tag)
          (total-bytes . ,total-bytes))))

(define (count-by-tag blocks)
  (doc 'type (-> (List Block) Alist))
  (doc 'description "Count blocks by tag")
  (let count-loop ([blocks blocks]
                   [counts '()])
       (if (null? blocks)
           counts
           (let* ([tag (block-tag (car blocks))]
                  [existing (assq tag counts)])
                 (count-loop (cdr blocks)
                             (if existing
                                 (map (lambda (pair)
                                              (if (eq? (car pair) tag)
                                                  (cons tag (+ 1 (cdr pair)))
                                                  pair))
                                      counts)
                                 (cons (cons tag 1) counts)))))))

(define (store-print-stats fs)
  (doc 'type (-> FSCap Void))
  (doc 'description "Print human-readable store statistics")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (let ([stats (store-stats fs)])
       (printf "Store Statistics:\n")
       (printf "  Total blocks: ~a\n" (cdr (assq 'total stats)))
       (printf "  Total bytes:  ~a\n" (cdr (assq 'total-bytes stats)))
       (printf "  By tag:\n")
       (for-each (lambda (pair)
                         (printf "    ~a: ~a\n" (car pair) (cdr pair)))
                 (cdr (assq 'by-tag stats)))))

(doc 'section 'graph-navigation)

(define (store-get-refs fs block)
  (doc 'type (-> FSCap Block (List Block)))
  (doc 'description "Get all blocks referenced by given block")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (let ([refs (block-refs block)])
       (let collect-refs ([i 0]
                          [result '()])
            (if (>= i (vector-length refs))
                (reverse result)
                (let ([ref-hash (vector-ref refs i)])
                     (let ([ref-block (store-get fs ref-hash)])
                          (collect-refs (+ i 1)
                                        (if ref-block
                                            (cons ref-block result)
                                            result))))))))

(define (store-get-referrers fs hash)
  (doc 'type (-> FSCap Hash (List Block)))
  (doc 'description "Get all blocks that reference given hash")
  (doc 'note "Alias for store-find-by-ref for clarity")
  (doc 'tier '(5 6))
  (doc 'export #t)
  (store-find-by-ref fs hash))

(doc 'section 'knowledge-graph-helpers)

(define (store-get-entities fs)
  (doc 'type (-> FSCap (List Block)))
  (doc 'description "Get all entity blocks")
  (doc 'tier 6)
  (doc 'export #t)
  (store-find-by-tag fs 'entity))

(define (store-get-relations fs)
  (doc 'type (-> FSCap (List Block)))
  (doc 'description "Get all relation blocks")
  (doc 'tier 6)
  (doc 'export #t)
  (store-find-by-tag fs 'relation))

(define (store-get-collections fs)
  (doc 'type (-> FSCap (List Block)))
  (doc 'description "Get all collection blocks")
  (doc 'tier 6)
  (doc 'export #t)
  (store-find-by-tag fs 'collection))

(printf "✓ Store API loaded\n")
(printf "  Functions available:\n")
(printf "    Core:   store-put!, store-get, store-exists?\n")
(printf "    Query:  store-find-by-tag, store-find-by-payload-contains\n")
(printf "    Graph:  store-get-refs, store-get-referrers\n")
(printf "    Stats:  store-stats, store-print-stats\n")
