(load "core/base/prelude.ss")
(load "core/blocks/block.ss")
(load "core/blocks/cas.ss")

(doc 'module 'boundary/bbs/blocks)
(doc 'description "BBS Block Creation Helpers - Creates CAS blocks for the bulletin board system")
(doc 'layer 'boundary)
(doc 'purity 'partial)
(doc 'dependencies '(core/base/prelude core/blocks/block core/blocks/cas))

(doc 'section 'block-tags)

(doc BBS-ISSUE 'type 'Symbol)
(doc BBS-ISSUE 'description "Block tag for issue entities")
(define BBS-ISSUE 'bbs/issue)

(doc BBS-EVENT 'type 'Symbol)
(doc BBS-EVENT 'description "Block tag for state change events (audit trail)")
(define BBS-EVENT 'bbs/event)

(doc BBS-COMMENT 'type 'Symbol)
(doc BBS-COMMENT 'description "Block tag for comments on issues")
(define BBS-COMMENT 'bbs/comment)

(doc BBS-DEP 'type 'Symbol)
(doc BBS-DEP 'description "Block tag for dependency relations (A blocks B)")
(define BBS-DEP 'bbs/dep)

(doc BBS-INDEX 'type 'Symbol)
(doc BBS-INDEX 'description "Block tag for root index of all issues")
(define BBS-INDEX 'bbs/index)

(doc BBS-POST 'type 'Symbol)
(doc BBS-POST 'description "Block tag for general posts (changelog, note, announcement)")
(define BBS-POST 'bbs/post)

(doc 'section 'issue-block)

(define (make-issue-block id title description status priority type labels
                          created-at created-by version prev-hash)
  (doc 'type '(-> String String String Symbol Int Symbol (List Symbol) String String Int (Option Bytevector) Block))
  (doc 'description "Create an issue block")
  (doc 'param 'id "Human-readable ID (e.g., 'fold-0001')")
  (doc 'param 'title "Issue title")
  (doc 'param 'description "Issue description")
  (doc 'param 'status "'open | 'in_progress | 'closed")
  (doc 'param 'priority "0-4 (0=critical, 4=backlog)")
  (doc 'param 'type "'task | 'bug | 'feature | 'epic")
  (doc 'param 'labels "List of label symbols")
  (doc 'param 'created-at "ISO 8601 timestamp")
  (doc 'param 'created-by "Username")
  (doc 'param 'version "Version number (increments on update)")
  (doc 'param 'prev-hash "Hash of previous version (or #f for first version)")
  (doc 'export #t)
  (let* ([payload-data `((id . ,id)
                         (title . ,title)
                         (description . ,description)
                         (status . ,status)
                         (priority . ,priority)
                         (type . ,type)
                         (labels . ,labels)
                         (created-at . ,created-at)
                         (created-by . ,created-by)
                         (version . ,version))]
         [payload (string->utf8 (format "~s" payload-data))]
         [refs (if prev-hash
                   (vector prev-hash)
                   (vector))])
    (make-block BBS-ISSUE payload refs)))

(define (issue-block-data blk)
  (doc 'type '(-> Block (Option Alist)))
  (doc 'description "Extract issue data from a block")
  (doc 'export #t)
  (if (and (block? blk) (eq? (block-tag blk) BBS-ISSUE))
      (read (open-input-string (utf8->string (block-payload blk))))
      #f))

(define (issue-block-prev blk)
  (doc 'type '(-> Block (Option Bytevector)))
  (doc 'description "Get the previous version hash from an issue block")
  (doc 'export #t)
  (let ([refs (block-refs blk)])
    (if (> (vector-length refs) 0)
        (vector-ref refs 0)
        #f)))

(doc 'section 'event-block)

(define (make-event-block issue-hash event-type old-value new-value timestamp actor)
  (doc 'type '(-> Bytevector Symbol Any Any String String Block))
  (doc 'description "Create an event block recording a state change")
  (doc 'param 'issue-hash "Hash of the issue this event relates to")
  (doc 'param 'event-type "'status-change | 'priority-change | 'title-change | etc.")
  (doc 'param 'old-value "Previous value")
  (doc 'param 'new-value "New value")
  (doc 'param 'timestamp "ISO 8601 timestamp")
  (doc 'param 'actor "Username who made the change")
  (doc 'export #t)
  (let* ([payload-data `((event-type . ,event-type)
                         (old-value . ,old-value)
                         (new-value . ,new-value)
                         (timestamp . ,timestamp)
                         (actor . ,actor))]
         [payload (string->utf8 (format "~s" payload-data))])
    (make-block BBS-EVENT payload (vector issue-hash))))

(define (event-block-data blk)
  (doc 'type '(-> Block (Option Alist)))
  (doc 'description "Extract event data from a block")
  (doc 'export #t)
  (if (and (block? blk) (eq? (block-tag blk) BBS-EVENT))
      (read (open-input-string (utf8->string (block-payload blk))))
      #f))

(doc 'section 'comment-block)

(define (make-comment-block issue-hash comment-id author text content-type created-at)
  (doc 'type '(-> Bytevector Int String String Symbol String Block))
  (doc 'description "Create a comment block")
  (doc 'param 'issue-hash "Hash of the issue")
  (doc 'param 'comment-id "Sequential comment ID within issue")
  (doc 'param 'author "Username")
  (doc 'param 'text "Comment text")
  (doc 'param 'content-type "'text | 'code | 'tool-result | 'thought")
  (doc 'param 'created-at "ISO 8601 timestamp")
  (doc 'export #t)
  (let* ([payload-data `((id . ,comment-id)
                         (author . ,author)
                         (text . ,text)
                         (content-type . ,content-type)
                         (created-at . ,created-at))]
         [payload (string->utf8 (format "~s" payload-data))])
    (make-block BBS-COMMENT payload (vector issue-hash))))

(define (comment-block-data blk)
  (doc 'type '(-> Block (Option Alist)))
  (doc 'description "Extract comment data from a block")
  (doc 'export #t)
  (if (and (block? blk) (eq? (block-tag blk) BBS-COMMENT))
      (read (open-input-string (utf8->string (block-payload blk))))
      #f))

(doc 'section 'dependency-block)

(define (make-dep-block blocker-hash blocked-hash)
  (doc 'type '(-> Bytevector Bytevector Block))
  (doc 'description "Create a dependency block: blocker-hash blocks blocked-hash. refs[0] = blocker, refs[1] = blocked")
  (doc 'export #t)
  (make-block BBS-DEP #vu8() (vector blocker-hash blocked-hash)))

(define (dep-block-blocker blk)
  (doc 'type '(-> Block Bytevector))
  (doc 'description "Get the blocker hash from a dep block")
  (doc 'export #t)
  (vector-ref (block-refs blk) 0))

(define (dep-block-blocked blk)
  (doc 'type '(-> Block Bytevector))
  (doc 'description "Get the blocked hash from a dep block")
  (doc 'export #t)
  (vector-ref (block-refs blk) 1))

(doc 'section 'index-block)

(define (make-index-block issue-hashes timestamp)
  (doc 'type '(-> (List Bytevector) String Block))
  (doc 'description "Create an index block aggregating all issue hashes")
  (doc 'param 'issue-hashes "List of all current issue hashes")
  (doc 'param 'timestamp "When index was created")
  (doc 'export #t)
  (let* ([payload-data `((count . ,(length issue-hashes))
                         (timestamp . ,timestamp))]
         [payload (string->utf8 (format "~s" payload-data))])
    (make-block BBS-INDEX payload (list->vector issue-hashes))))

(define (index-block-data blk)
  (doc 'type '(-> Block (Option Alist)))
  (doc 'description "Extract index data from a block")
  (doc 'export #t)
  (if (and (block? blk) (eq? (block-tag blk) BBS-INDEX))
      (read (open-input-string (utf8->string (block-payload blk))))
      #f))

(define (index-block-issues blk)
  (doc 'type '(-> Block (Vector Bytevector)))
  (doc 'description "Get the issue hashes from an index block")
  (doc 'export #t)
  (block-refs blk))

(doc 'section 'board-descriptor-block)

(doc BBS-BOARD 'type 'Symbol)
(doc BBS-BOARD 'description "Block tag for board descriptor entities")
(define BBS-BOARD 'bbs/board)

(doc 'section 'forum-blocks)

(doc BBS-TOPIC 'type 'Symbol)
(doc BBS-TOPIC 'description "Block tag for forum topic entities")
(define BBS-TOPIC 'bbs/topic)

(doc BBS-REPLY 'type 'Symbol)
(doc BBS-REPLY 'description "Block tag for forum reply entities")
(define BBS-REPLY 'bbs/reply)

(define (make-topic-block id title body author created-at status version prev-hash)
  (doc 'type '(-> String String String String String Symbol Int (Option Bytevector) Block))
  (doc 'description "Create a forum topic block")
  (doc 'export #t)
  (let* ([payload-data `((id . ,id)
                          (title . ,title)
                          (body . ,body)
                          (author . ,author)
                          (created-at . ,created-at)
                          (status . ,status)
                          (version . ,version))]
         [payload (string->utf8 (format "~s" payload-data))]
         [refs (if prev-hash (vector prev-hash) (vector))])
    (make-block BBS-TOPIC payload refs)))

(define (topic-block-data blk)
  (doc 'type '(-> Block (Option Alist)))
  (doc 'description "Extract topic data from a block")
  (doc 'export #t)
  (if (and (block? blk) (eq? (block-tag blk) BBS-TOPIC))
      (read (open-input-string (utf8->string (block-payload blk))))
      #f))

(define (topic-block-prev blk)
  (doc 'type '(-> Block (Option Bytevector)))
  (doc 'description "Get the previous version hash from a topic block")
  (doc 'export #t)
  (let ([refs (block-refs blk)])
    (if (> (vector-length refs) 0)
        (vector-ref refs 0)
        #f)))

(define (make-reply-block topic-hash reply-id body author created-at parent-hash)
  (doc 'type '(-> Bytevector String String String String (Option Bytevector) Block))
  (doc 'description "Create a forum reply block. refs[0] = topic or parent reply hash")
  (doc 'param 'parent-hash "Hash of parent (topic or reply for nested threading)")
  (doc 'export #t)
  (let* ([payload-data `((id . ,reply-id)
                          (body . ,body)
                          (author . ,author)
                          (created-at . ,created-at))]
         [payload (string->utf8 (format "~s" payload-data))]
         [refs (if parent-hash
                   (vector topic-hash parent-hash)
                   (vector topic-hash))])
    (make-block BBS-REPLY payload refs)))

(define (reply-block-data blk)
  (doc 'type '(-> Block (Option Alist)))
  (doc 'description "Extract reply data from a block")
  (doc 'export #t)
  (if (and (block? blk) (eq? (block-tag blk) BBS-REPLY))
      (read (open-input-string (utf8->string (block-payload blk))))
      #f))

(define (reply-block-topic-hash blk)
  (doc 'type '(-> Block Bytevector))
  (doc 'description "Get the topic hash from a reply block (refs[0])")
  (doc 'export #t)
  (vector-ref (block-refs blk) 0))

(define (make-board-block slug board-type id-prefix description created-at created-by)
  (doc 'type '(-> String Symbol String String String String Block))
  (doc 'description "Create a board descriptor block for CAS storage")
  (doc 'export #t)
  (let* ([payload-data `((name . ,slug)
                          (slug . ,slug)
                          (board-type . ,board-type)
                          (id-prefix . ,id-prefix)
                          (description . ,description)
                          (created-at . ,created-at)
                          (created-by . ,created-by))]
         [payload (string->utf8 (format "~s" payload-data))])
    (make-block BBS-BOARD payload (vector))))

(define (board-block-data blk)
  (doc 'type '(-> Block (Option Alist)))
  (doc 'description "Extract board descriptor data from a block")
  (doc 'export #t)
  (if (and (block? blk) (eq? (block-tag blk) BBS-BOARD))
      (read (open-input-string (utf8->string (block-payload blk))))
      #f))

(doc 'section 'post-block)

(define (make-post-block id title body post-type tags created-at author version prev-hash)
  (doc 'type '(-> String String String Symbol (List Symbol) String String Int (Option Bytevector) Block))
  (doc 'description "Create a post block for changelogs, notes, announcements")
  (doc 'param 'id "Human-readable ID (e.g., 'post-001')")
  (doc 'param 'title "Post title")
  (doc 'param 'body "Post body (markdown)")
  (doc 'param 'post-type "'changelog | 'note | 'announcement | 'session-summary")
  (doc 'param 'tags "List of tag symbols")
  (doc 'param 'created-at "ISO 8601 timestamp")
  (doc 'param 'author "Username")
  (doc 'param 'version "Version number (increments on edit)")
  (doc 'param 'prev-hash "Hash of previous version (or #f for first version)")
  (doc 'export #t)
  (let* ([payload-data `((id . ,id)
                         (title . ,title)
                         (body . ,body)
                         (post-type . ,post-type)
                         (tags . ,tags)
                         (created-at . ,created-at)
                         (author . ,author)
                         (version . ,version))]
         [payload (string->utf8 (format "~s" payload-data))]
         [refs (if prev-hash
                   (vector prev-hash)
                   (vector))])
    (make-block BBS-POST payload refs)))

(define (post-block-data blk)
  (doc 'type '(-> Block (Option Alist)))
  (doc 'description "Extract post data from a block")
  (doc 'export #t)
  (if (and (block? blk) (eq? (block-tag blk) BBS-POST))
      (read (open-input-string (utf8->string (block-payload blk))))
      #f))

(define (post-block-prev blk)
  (doc 'type '(-> Block (Option Bytevector)))
  (doc 'description "Get the previous version hash from a post block")
  (doc 'export #t)
  (let ([refs (block-refs blk)])
    (if (> (vector-length refs) 0)
        (vector-ref refs 0)
        #f)))
