; ============================================================
; Minimal Exports
; Only the essential prelude functions
; Additional functions available via (load "stdlib/...")
; ============================================================

(list
 ; Core HOFs
 (cons 'map map)
 (cons 'filter filter)
 (cons 'foldl foldl)
 (cons 'foldr foldr)
 (cons 'any any)
 (cons 'all all)
 (cons 'take-while take-while)
 (cons 'drop-while drop-while)
 (cons 'zip-with zip-with)

 ; Function combinators
 (cons 'id id)
 (cons 'const const)
 (cons 'compose compose)
 (cons 'pipe pipe)
 (cons 'flip flip)
 (cons 'complement complement)
 (cons 'curry2 curry2)
 (cons 'uncurry2 uncurry2)
 (cons 'on on)
 (cons 'juxt juxt)
 (cons 'compose-n compose-n)
 (cons 'pipe-n pipe-n)
 (cons 'apply-both apply-both)
 (cons 'converge converge)
 (cons 'partial2 partial2)
 (cons 'partial2-right partial2-right)
 (cons 'arity-1 arity-1)
 (cons 'apply-n apply-n)
 (cons 'bounce bounce)
 (cons 'bounce? bounce?)
 (cons 'done done)
 (cons 'trampoline trampoline)
 (cons 'Y Y)
 (cons 'constantly constantly)
 (cons 'negate-pred negate-pred)
 (cons 'juxtapose juxtapose)
 (cons 'memo-table memo-table)
 (cons 'memo-lookup memo-lookup)
 (cons 'memo-insert memo-insert)
 (cons 'with-memo with-memo)

 ; car/cdr compositions
 (cons 'caar caar)
 (cons 'cadr cadr)
 (cons 'cdar cdar)
 (cons 'cddr cddr)
 (cons 'caaar caaar)
 (cons 'caadr caadr)
 (cons 'cadar cadar)
 (cons 'caddr caddr)
 (cons 'cdaar cdaar)
 (cons 'cdadr cdadr)
 (cons 'cddar cddar)
 (cons 'cdddr cdddr)
 (cons 'caaaar caaaar)
 (cons 'caaadr caaadr)
 (cons 'caadar caadar)
 (cons 'caaddr caaddr)
 (cons 'cadaar cadaar)
 (cons 'cadadr cadadr)
 (cons 'caddar caddar)
 (cons 'cadddr cadddr)
 (cons 'cdaaar cdaaar)
 (cons 'cdaadr cdaadr)
 (cons 'cdadar cdadar)
 (cons 'cdaddr cdaddr)
 (cons 'cddaar cddaar)
 (cons 'cddadr cddadr)
 (cons 'cdddar cdddar)
 (cons 'cddddr cddddr)

 ; Equality
 (cons 'eqv? eqv?)
 (cons 'equal? equal?)
 (cons 'equal-by equal-by)
 (cons 'member? member?)
 (cons 'all-equal? all-equal?)

 ; Maybe monad
 (cons 'just just)
 (cons 'nothing nothing)
 (cons 'just? just?)
 (cons 'nothing? nothing?)
 (cons 'from-just from-just)
 (cons 'maybe-map maybe-map)
 (cons 'maybe-bind maybe-bind)
 (cons 'maybe-apply maybe-apply)
 (cons 'maybe-or maybe-or)
 (cons 'maybe-and maybe-and)
 (cons 'from-maybe from-maybe)
 (cons 'maybe-to-list maybe-to-list)
 (cons 'list-to-maybe list-to-maybe)
 (cons 'cat-maybes cat-maybes)
 (cons 'map-maybe map-maybe)
 (cons 'maybe maybe)
 (cons 'from-maybe-simple from-maybe-simple)
 (cons 'map-maybe-simple map-maybe-simple)
 (cons 'cat-maybes-simple cat-maybes-simple)

 ; Either monad
 (cons 'left left)
 (cons 'right right)
 (cons 'left? left?)
 (cons 'right? right?)
 (cons 'from-left from-left)
 (cons 'from-right from-right)
 (cons 'ok ok)
 (cons 'err err)
 (cons 'ok? ok?)
 (cons 'err? err?)
 (cons 'ok-value ok-value)
 (cons 'err-value err-value)
 (cons 'either either)
 (cons 'either-map either-map)
 (cons 'either-map-left either-map-left)
 (cons 'either-bind either-bind)
 (cons 'either-apply either-apply)
 (cons 'from-either from-either)
 (cons 'either-to-maybe either-to-maybe)
 (cons 'maybe-to-either maybe-to-either)
 (cons 'lefts lefts)
 (cons 'rights rights)
 (cons 'partition-eithers partition-eithers)
 (cons 'sequence-either sequence-either)
 (cons 'traverse-either traverse-either)
)
