((name "autodiff")
 (purpose "Automatic differentiation")
 (description "Reverse-mode automatic differentiation (backpropagation)
using computational graphs. Supports higher-order derivatives and
provides a differentiable type class for extensibility.")
 (modules
  ((comp-graph.ss "Computational graph construction")
   (reverse-diff.ss "Reverse-mode AD (backpropagation)")
   (higher-order-diff.ss "Higher-order derivative computation")
   (differentiable.ss "Differentiable type class")
   (differentiable-signal.ss "Differentiable signal processing")
   (sparse-autodiff.ss "Sparse autodiff for large systems")
   (typed-gradients.ss "Type-safe gradient computation")
   (profiling.ss "Performance profiling and debugging")
   (symbolic-diff.ss "Bridge symbolic expressions to traced autodiff")))
 (dependencies (base linalg fp/symbolic))
 (algorithm "Reverse-mode AD via tape-based computational graphs"))
