(readme statistics
(summary "Comprehensive statistical modeling library for The Fold")
(overview "The statistics skill provides a complete suite of statistical tools including:\n    - Linear regression (OLS, WLS) with full diagnostics\n    - Generalized Linear Models (GLM) via IRLS\n    - Regularized regression (Ridge, Lasso, Elastic Net)\n    - Time series analysis (AR, MA, exponential smoothing)\n    - Hypothesis testing (t-tests, chi-squared, ANOVA, F-tests)\n\n    All regression models provide standard errors, t-statistics, and p-values.\n    GLM implementation uses Iteratively Reweighted Least Squares (IRLS) which\n    computes SEs directly from the inverse Hessian.\n\n    Logistic regression is implemented as a GLM wrapper:\n    (logistic-fit X y criteria) = (glm-fit binomial-family logit-link X y criteria)")
(usage 
  ((linear-regression "Fit linear model with OLS:" "(define model (linear-model-fit X y))" "(define predictions (linear-model-predict model X-new))" "(define r-squared (lm-r-squared model))" "(define coefficients (lm-coefficients model))")
  (logistic-regression "Fit binary classifier via GLM:" "(define model (logistic-fit X y '((max-iter 100) (tol 1e-6))))" "(define probs (glm-predict-proba model X-new))" "(define classes (glm-predict model X-new))")
  (regularized-regression "Fit with L1/L2 regularization:" "(define ridge-model (ridge-fit X y lambda))" "(define lasso-model (lasso-fit X y lambda criteria))" "(define elastic (elastic-net-fit X y lambda alpha criteria))" "(define best-lambda (cross-validate-lambda X y 'ridge k-folds lambdas))")
  (time-series "AR and exponential smoothing:" "(define ar-model (ar-fit xs p))" "(define forecasts (ar-forecast ar-model xs h))" "(define hw-model (holt-winters xs 0.3 0.1 0.2 12 'additive))" "(define hw-forecasts (hw-forecast hw-model 12))")
  (hypothesis-tests "Statistical hypothesis testing:" "(define t-result (t-test-two-sample xs ys))" "(define anova-result (anova-one-way groups))" "(define chi-result (chi-squared-test-independence contingency-table))")))
(architecture "Three-layer structure following Lattice conventions:\n\n    core/\n    ├── result-types.ss    # Extensible result structures\n    ├── summary-stats.ss   # Descriptive statistics\n    ├── design-matrix.ss   # Design matrix utilities\n    └── diagnostics.ss     # Leverage, Cook's D, VIF\n\n    regression/\n    ├── linear.ss          # OLS, WLS\n    ├── regularized.ss     # Ridge, Lasso, Elastic Net\n    ├── glm.ss             # GLM via IRLS\n    ├── families.ss        # Gaussian, Binomial, Poisson, Gamma\n    └── link-functions.ss  # Identity, Logit, Log, Probit\n\n    hypothesis/\n    ├── distributions.ss   # t, chi-sq, F using special-functions.ss\n    ├── t-test.ss          # t-tests\n    ├── chi-squared.ss     # Chi-squared tests\n    ├── anova.ss           # ANOVA\n    └── f-test.ss          # F-tests\n\n    timeseries/\n    ├── differencing.ss    # Differencing, Box-Cox\n    ├── acf-pacf.ss        # ACF, PACF, Durbin-Levinson\n    ├── ar.ss              # AR(p) via Yule-Walker\n    ├── ma.ss              # MA(q) via innovations\n    ├── exponential.ss     # Holt-Winters\n    └── forecast.ss        # Accuracy metrics")
(dependencies 
  ((linalg "Matrix operations, least squares")
  (fp/numeric "Special functions (betainc, gammainc-reg, erf)")))
(key-decisions 
  ((glm-over-separate-logistic "Logistic regression is a thin wrapper around GLM (binomial + logit).\n      This avoids code duplication and ensures consistent SE computation.")
  (irls-over-gradient-descent "GLM uses IRLS instead of gradient descent because:\n      1. IRLS provides SEs directly from (X'WX)^-1\n      2. Faster convergence for well-conditioned problems\n      3. No learning rate tuning required")
  (ar-over-arima "AR + exponential smoothing instead of full ARIMA because:\n      1. More numerically stable\n      2. Yule-Walker has closed-form solution\n      3. ARIMA can be added later as extension")
  (coordinate-descent-for-lasso "Lasso uses coordinate descent with soft-thresholding because\n      L1 penalty has undefined gradient at 0.")))
(testing "(load \"lattice/statistics/test-statistics.ss\")\n    (run-all-tests)"))
