(load "lattice/meta/search.ss")
(load "lattice/meta/analytics.ss")
(load "lattice/meta/inspect.ss")
(load "boundary/meta/persist-io.ss")
(load "boundary/meta/source-loc-io.ss")
(load "boundary/meta/docstrings-io.ss")
(load "boundary/meta/kg-io.ss")
(load "boundary/meta/exports-io.ss")
(load "boundary/meta/inspect-io.ss")
(load "boundary/introspect/exports.ss")

(doc 'module 'meta)
(doc 'description "Unified entry point for lattice meta-tooling modules. Loads all lattice navigation capabilities.")
(doc 'layer 'lattice)
(doc 'purity 'partial)

(doc 'section 'initialization)

(doc lattice-init! 'type (-> Void))
(doc lattice-init! 'description "Initialize the lattice tooling (build KG and search indices). Uses cache if valid, otherwise rebuilds and caches")
(define (lattice-init!)
  (if (lattice-load-cache!)
      ;; Cache loaded - docstrings and source-locs already restored
      (begin
        (lattice-index!)
        (printf "\nLattice tooling initialized (from cache)!\n"))
      ;; No valid cache, full rebuild
      (begin
        (kg-build!)
        (lattice-index!)
        (build-source-location-cache!)
        (lattice-save-cache!)
        (printf "\nLattice tooling initialized!\n")))
  (printf "  Use (lf \"query\") to search\n")
  (printf "  Use (li 'skill) to inspect a skill\n")
  (printf "  Use (lef \"file.ss\") to list exports from any file\n")
  (printf "  Use (lt 'skill) to list tests\n")
  (printf "  Use (lsrc 'fn) for source location\n")
  (printf "  Use (ls) for statistics\n")
  (printf "  Use (lh) for health check\n"))

(doc lattice-init-quiet! 'type (-> Void))
(doc lattice-init-quiet! 'description "Initialize silently (for REPL startup). Uses cache if valid - very fast startup")
(define (lattice-init-quiet!)
  (if (lattice-load-cache!)
      ;; Cache loaded - docstrings and source-locs already restored
      ;; Just build the BM25 indices (fast, in-memory only)
      (lattice-index!)
      ;; No cache - full rebuild
      (begin
        (kg-build!)
        (lattice-index!)
        (build-source-location-cache!)
        (lattice-save-cache!))))

(doc lattice-ensure! 'type (-> Void))
(doc lattice-ensure! 'description "Initialize only if not already ready. Use this in tests.")
(define (lattice-ensure!)
  (unless *search-ready*
          (lattice-init!)))

(doc lattice-init-fresh! 'type (-> Void))
(doc lattice-init-fresh! 'description "Force full rebuild, ignoring cache")
(define (lattice-init-fresh!)
  (kg-build!)
  (lattice-index!)
  (build-source-location-cache!)
  (lattice-save-cache!)
  (printf "\nLattice tooling initialized (fresh build)!\n")
  (printf "  Use (lf \"query\") to search\n")
  (printf "  Use (li 'skill) to inspect a skill\n")
  (printf "  Use (lef \"file.ss\") to list exports from any file\n")
  (printf "  Use (lt 'skill) to list tests\n")
  (printf "  Use (lsrc 'fn) for source location\n")
  (printf "  Use (ls) for statistics\n")
  (printf "  Use (lh) for health check\n"))

(doc 'section 'source-location)

(doc lsrc 'type (-> Symbol (Maybe String)))
(doc lsrc 'description "Quick source location lookup - prints \"file:line\" format")
(define (lsrc sym)
  (let ([loc (format-source-location sym)])
       (if loc
           loc
           (printf "Symbol not found: ~a\n" sym))))

(doc 'section 'quick-reference)

(define (lattice-help)
  (doc 'type (-> Void))
  (doc 'description "Print quick reference for lattice meta-tooling commands")
  (printf "\nLattice Meta-Tooling Quick Reference\n")
  (printf "====\n\n")
  (printf "INITIALIZATION:\n")
  (printf "  (lattice-init!)           - Init with caching (fast if unchanged)\n")
  (printf "  (lattice-init-fresh!)     - Force full rebuild\n\n")
  (printf "SEARCH:\n")
  (printf "  (lf \"query\")              - Full-text search\n")
  (printf "  (lfe 'symbol)             - Exact lookup (falls back to substring)\n")
  (printf "  (lfp 'prefix)             - Prefix search\n")
  (printf "  (lfs 'substr)             - Substring search\n")
  (printf "  (lattice-complete \"pre\")  - Autocomplete\n\n")
  (printf "DEPENDENCIES:\n")
  (printf "  (ld 'skill)               - Show what skill depends on\n")
  (printf "  (lu 'skill)               - Show what uses this skill\n")
  (printf "  (lattice-path 'a 'b)      - Find path between skills\n")
  (printf "  (lattice-graph)           - Print full DAG\n\n")
  (printf "CYCLE DETECTION:\n")
  (printf "  (lc 'skill)               - Check skill for cycles\n")
  (printf "  (lattice-would-cycle? 'a 'b) - Would a->b create cycle?\n")
  (printf "  (lattice-check-deps 'skill)  - Validate skill's deps\n")
  (printf "  (lattice-validate-all)    - Validate all skills\n\n")
  (printf "INSPECTION:\n")
  (printf "  (li 'skill)               - Full skill description\n")
  (printf "  (le 'skill)               - List exports (from manifest)\n")
  (printf "  (lef \"file.ss\")           - List exports (from any file)\n")
  (printf "  (lm 'skill)               - List modules\n")
  (printf "  (lsrc 'fn)                - Source location (file:line)\n")
  (printf "  (lattice-summary)         - One-line summary of all skills\n\n")
  (printf "TESTING:\n")
  (printf "  (lt 'skill)               - List test files\n")
  (printf "  (ltr 'skill)              - Run skill tests\n")
  (printf "  (lattice-tests 'skill)    - Get test file list\n")
  (printf "  (lattice-tests-run 'skill) - Run tests (structured result)\n")
  (printf "  (lattice-tests-summary)   - Test coverage overview\n\n")
  (printf "ANALYTICS:\n")
  (printf "  (ls)                      - Lattice statistics\n")
  (printf "  (lh)                      - Health check\n")
  (printf "  (lattice-coverage-pretty) - Coverage report\n")
  (printf "  (lattice-hubs)            - Most-used skills\n\n")
  (printf "STRUCTURAL:\n")
  (printf "  (lattice-roots)           - Dependency-free skills\n")
  (printf "  (lattice-tier-0)          - Tier 0 foundational skills\n")
  (printf "  (lattice-leaves)          - Skills with no dependents\n")
  (printf "  (lattice-tiers)           - Skills grouped by tier\n"))

(doc 'section 'repl-interface)

(meta-printf "\nmeta.ss loaded — Unified lattice tooling\n")
(meta-printf "  (lattice-init!)  - Initialize (build KG + indices)\n")
(meta-printf "  (lattice-help)   - Show quick reference\n")
