(load "core/types/gadt.ss")

(doc 'module 'gadt-infer)
(doc 'description "DEPRECATED: Backwards-compatibility stub. This file has been merged into gadt.ss. Load gadt.ss for all GADT functionality including inference.")
(doc 'layer 'core)
(doc 'deprecated #t)

(doc 'note "All GADT inference functions are now defined in gadt.ss:")
(doc 'note "- gadt-infer-synth")
(doc 'note "- gadt-infer-synth-case")
(doc 'note "- gadt-infer-check-ctors")
(doc 'note "- gadt-infer-synth-clauses")
(doc 'note "- gadt-infer-synth-clause")
(doc 'note "- reset-gadt-registry!")
(doc 'note "- register-gadt!")
(doc 'note "- lookup-gadt")
(doc 'note "- gadt-define-test-gadts!")
