(load "core/types/rank-n.ss")

(doc 'module 'rank-n-infer)
(doc 'description "DEPRECATED: Backwards-compatibility stub. This file has been merged into rank-n.ss. Load rank-n.ss for all rank-N type functionality including inference.")
(doc 'layer 'core)
(doc 'deprecated #t)

(doc 'note "All rank-N inference functions are now defined in rank-n.ss:")
(doc 'note "- forall-well-formed?")
(doc 'note "- forall-vars, forall-var-kinds, forall-body")
(doc 'note "- rank-n-instantiate")
(doc 'note "- rank-n-generalize")
(doc 'note "- rank-n-subsumes?, rank-n-subsumes-result")
(doc 'note "- fresh-rank-n-var, reset-rank-n-fresh!")
(doc 'note "- peek-argument-structure, should-delay-instantiation?")
(doc 'note "- rank-n-skolem?, type-contains-skolem?")
(doc 'note "- impredicative-unify-with")
(doc 'note "- rank-n-infer-synth, rank-n-check")
(doc 'note "- rank-n-typeof, rank-n-typecheck")
