;;; @module rlm2-worker-prelude
;;; @description Utility functions loaded into IPC worker session.
;;; Loaded by rlm2-drive.ss — requires fold-ipc-eval.

;;; ====
;;; Worker Prelude (reused from v1)
;;; ====
;;; Loads string utilities into the IPC worker session.
;;; Identical to v1 — the worker is the same.

(define (rlm2-init-worker-prelude!)
  (fold-ipc-eval
    (string-append
      "(begin"
      "  (define (rlm-split-lines s)"
      "    (let loop ([chars (string->list s)] [current '()] [lines '()])"
      "      (cond"
      "        [(null? chars) (reverse (cons (list->string (reverse current)) lines))]"
      "        [(char=? (car chars) #\\newline)"
      "         (loop (cdr chars) '() (cons (list->string (reverse current)) lines))]"
      "        [else (loop (cdr chars) (cons (car chars) current) lines)])))"
      "  (define (rlm-string-contains? s sub)"
      "    (let ([s-len (string-length s)] [sub-len (string-length sub)])"
      "      (if (> sub-len s-len) #f"
      "          (let loop ([i 0])"
      "            (cond [(> (+ i sub-len) s-len) #f]"
      "                  [(string=? (substring s i (+ i sub-len)) sub) #t]"
      "                  [else (loop (+ i 1))])))))"
      "  (define (rlm-extract-after s marker)"
      "    (let ([s-len (string-length s)] [m-len (string-length marker)])"
      "      (let loop ([i 0])"
      "        (cond [(> (+ i m-len) s-len) #f]"
      "              [(string=? (substring s i (+ i m-len)) marker)"
      "               (let ([rest (substring s (+ i m-len) s-len)])"
      "                 (let trim ([j 0])"
      "                   (cond [(>= j (string-length rest)) rest]"
      "                         [(char-whitespace? (string-ref rest j)) (trim (+ j 1))]"
      "                         [else (substring rest j (string-length rest))])))]"
      "              [else (loop (+ i 1))]))))"
      "  (define (rlm-flatten lst)"
      "    (cond [(null? lst) '()]"
      "          [(null? (car lst)) (rlm-flatten (cdr lst))]"
      "          [(pair? (car lst)) (append (rlm-flatten (car lst)) (rlm-flatten (cdr lst)))]"
      "          [else (cons (car lst) (rlm-flatten (cdr lst)))]))"
      "  (define (rlm-deduplicate lst)"
      "    (let loop ([l lst] [seen '()] [acc '()])"
      "      (if (null? l) (reverse acc)"
      "          (if (member (car l) seen)"
      "              (loop (cdr l) seen acc)"
      "              (loop (cdr l) (cons (car l) seen) (cons (car l) acc))))))"
      "  (define string-contains? rlm-string-contains?)"
      "  (define split-lines rlm-split-lines)"
      "  (define flatten rlm-flatten)"
      "  (define deduplicate rlm-deduplicate)"
      "  (define remove-duplicates rlm-deduplicate)"
      "  (define extract-after rlm-extract-after)"
      "  (define first car)"
      "  (define second cadr)"
      "  (define third caddr)"
      "  (define fourth cadddr)"
      "  (define (fifth lst) (car (cddddr lst)))"
      "  (define (rest lst) (cdr lst))"
      "  (define (last lst) (if (null? (cdr lst)) (car lst) (last (cdr lst))))"
      "  (define rest cdr)"
      "  (define (iota n) (let loop ([i (- n 1)] [acc '()]) (if (< i 0) acc (loop (- i 1) (cons i acc)))))"
      "  (define (build-list n f) (map f (iota n)))"
      "  (define (sorted lst pred) (list-sort pred lst))"
      "  (define (list<? a b)"
      "    (cond [(and (null? a) (null? b)) #f]"
      "          [(null? a) #t]"
      "          [(null? b) #f]"
      "          [(string<? (if (string? (car a)) (car a) (format \"~a\" (car a)))"
      "                     (if (string? (car b)) (car b) (format \"~a\" (car b)))) #t]"
      "          [(string=? (if (string? (car a)) (car a) (format \"~a\" (car a)))"
      "                     (if (string? (car b)) (car b) (format \"~a\" (car b))))"
      "           (list<? (cdr a) (cdr b))]"
      "          [else #f]))"
      "  (define (filter-map f lst)"
      "    (let loop ([xs lst] [acc '()])"
      "      (if (null? xs) (reverse acc)"
      "          (let ([result (f (car xs))])"
      "            (if result"
      "                (loop (cdr xs) (cons result acc))"
      "                (loop (cdr xs) acc))))))"
      "  (define (string-split str delim)"
      "    (if (char? delim)"
      "        (let ([len (string-length str)])"
      "          (let loop ([i 0] [start 0] [acc '()])"
      "            (cond [(= i len) (reverse (cons (substring str start len) acc))]"
      "                  [(char=? (string-ref str i) delim)"
      "                   (loop (+ i 1) (+ i 1) (cons (substring str start i) acc))]"
      "                  [else (loop (+ i 1) start acc)])))"
      "        (let ([dlen (string-length delim)] [slen (string-length str)])"
      "          (if (= dlen 0) (list str)"
      "              (if (= dlen 1) (string-split str (string-ref delim 0))"
      "                  (let loop ([i 0] [start 0] [acc '()])"
      "                    (cond [(> (+ i dlen) slen)"
      "                           (reverse (cons (substring str start slen) acc))]"
      "                          [(string=? (substring str i (+ i dlen)) delim)"
      "                           (loop (+ i dlen) (+ i dlen) (cons (substring str start i) acc))]"
      "                          [else (loop (+ i 1) start acc)])))))))"
      "  (define (string-trim str)"
      "    (let ([len (string-length str)])"
      "      (let ([s (let loop ([i 0])"
      "                 (if (and (< i len) (char-whitespace? (string-ref str i)))"
      "                     (loop (+ i 1)) i))])"
      "        (let ([e (let loop ([i len])"
      "                   (if (and (> i s) (char-whitespace? (string-ref str (- i 1))))"
      "                       (loop (- i 1)) i))])"
      "          (substring str s e)))))"
      "  (define (string-prefix? prefix str)"
      "    (and (>= (string-length str) (string-length prefix))"
      "         (string=? (substring str 0 (string-length prefix)) prefix)))"
      "  (define (string-suffix? suffix str)"
      "    (let ([slen (string-length str)] [xlen (string-length suffix)])"
      "      (and (>= slen xlen)"
      "           (string=? (substring str (- slen xlen) slen) suffix))))"
      "  (define (take lst n)"
      "    (if (or (null? lst) (<= n 0)) '()"
      "        (cons (car lst) (take (cdr lst) (- n 1)))))"
      "  (define (drop lst n)"
      "    (if (or (null? lst) (<= n 0)) lst"
      "        (drop (cdr lst) (- n 1))))"
      "  (define (cartesian-product xs ys)"
      "    (apply append (map (lambda (x) (map (lambda (y) (list x y)) ys)) xs)))"
      "  (define (string-replace str old new)"
      "    (let ([s-len (string-length str)] [o-len (string-length old)])"
      "      (if (= o-len 0) str"
      "          (let loop ([i 0] [acc '()])"
      "            (cond [(> (+ i o-len) s-len)"
      "                   (apply string-append (reverse (cons (substring str i s-len) acc)))]"
      "                  [(string=? (substring str i (+ i o-len)) old)"
      "                   (loop (+ i o-len) (cons new acc))]"
      "                  [else (loop (+ i 1)"
      "                              (cons (string (string-ref str i)) acc))])))))"
      "  (define (string-join lst sep)"
      "    (if (null? lst) \"\""
      "        (let loop ([rest (cdr lst)] [acc (car lst)])"
      "          (if (null? rest) acc"
      "              (loop (cdr rest) (string-append acc sep (car rest)))))))"
      "  (define (string-index str ch)"
      "    (let ([len (string-length str)])"
      "      (let loop ([i 0])"
      "        (cond [(= i len) #f]"
      "              [(char=? (string-ref str i) ch) i]"
      "              [else (loop (+ i 1))]))))"
      "  (define (string-index-of str sub)"
      "    (let ([slen (string-length str)] [sublen (string-length sub)])"
      "      (let loop ([i 0])"
      "        (cond [(> (+ i sublen) slen) #f]"
      "              [(string=? (substring str i (+ i sublen)) sub) i]"
      "              [else (loop (+ i 1))]))))"
      "  (define (substr str start . rest)"
      "    (if (null? rest)"
      "        (substring str start (string-length str))"
      "        (substring str start (car rest))))"
      "  (void))"))
  (void))
