(load "lattice/sim/dynamics/attractor-render.ss")

(doc 'module 'animation-io)
(doc 'description "Terminal animation playback for attractor frame data")
(doc 'layer 'boundary)
(doc 'purity 'partial)

(define (play-animation frames delay-ms)
  (doc 'export #t)
  (doc 'type '(-> (List String) Number Void))
  (doc 'description "Play animation in terminal with delay between frames")
  (for-each (lambda (frame)
                    (display "\x1b;[2J\x1b;[H")
                    (display frame)
                    (flush-output-port (current-output-port))
                    (let ([start (current-time)])
                         (let loop ()
                              (when (< (- (current-time) start) (/ delay-ms 1000.0))
                                    (loop)))))
            frames))

(define (loop-animation frames delay-ms n-loops)
  (doc 'export #t)
  (doc 'type '(-> (List String) Number Nat Void))
  (doc 'description "Loop animation n times")
  (do ([i 0 (+ i 1)])
      ((>= i n-loops))
      (play-animation frames delay-ms)))
