(load "boundary/ui/ansi.ss")

(doc 'module 'ansi-test-output)
(doc 'description "Colored Test Output - Enhances the test framework with ANSI colored output. Load this file AFTER test-framework.ss to enable colors.")
(doc 'layer 'boundary)
(doc 'purity 'partial)
(doc 'dependencies '(boundary/ui/ansi core/testing/test-framework))

(doc 'section 'ansi-output-helpers)

(doc pass-indicator 'type 'String)
(doc pass-indicator 'description "Green checkmark for passing tests")
(define pass-indicator
  (string-append (style->ansi (style-fg color-green)) "✓" ansi-reset))

(doc fail-indicator 'type 'String)
(doc fail-indicator 'description "Red X for failing tests")
(define fail-indicator
  (string-append (style->ansi (style-fg color-red)) "✗" ansi-reset))

(define (colored-text style str)
  (doc 'type (-> Style String String))
  (doc 'description "Apply ANSI color style to text")
  (string-append (style->ansi style) str ansi-reset))

(doc 'section 'override-test-framework-output)

(define (name->string name)
  (doc 'type (-> Any String))
  (doc 'description "Convert a test name to string (handles both symbols and strings)")
  (if (symbol? name)
      (symbol->string name)
      (format "~a" name)))

(doc 'note "We redefine key functions from test-framework.ss with colors. This works because Scheme allows redefinition at the top level.")

(set! run-test
  (lambda (name test-thunk)
    (set-name! name)
    (let ([initial-fail-count (ctx-failed)])
      (guard (exn [else
                   (inc-failed!)
                   (display "    ")
                   (display fail-indicator)
                   (display " ")
                   (display (colored-text (style-fg color-white) (name->string name)))
                   (display (colored-text style-dim " — EXCEPTION: "))
                   (display (colored-text (style-fg color-red)
                             (if (condition? exn)
                                 (condition-message exn)
                                 (format "~a" exn))))
                   (newline)])
             (test-thunk))
      (when (= initial-fail-count (ctx-failed))
            (inc-passed!)
            (display "    ")
            (display pass-indicator)
            (display " ")
            (display (name->string name))
            (newline)))))

(set! run-group
  (lambda (group-name)
    (let ([group-entry (assq group-name *test-registry*)])
      (if group-entry
          (let ([tests (reverse (cdr group-entry))])
            (display "  ")
            (display (colored-text (make-style color-cyan #f #t #f #f #f)
                       (string-append "Group: " (symbol->string group-name))))
            (newline)
            (for-each (lambda (test)
                        (run-test (car test) (cdr test)))
                      tests))
          (begin
            (display "  ")
            (display (colored-text (style-fg color-yellow) "Warning: "))
            (display "No tests found for group ")
            (display group-name)
            (newline))))))

(set! print-summary
  (lambda ()
    (newline)
    (display (colored-text (make-style color-blue #f #t #f #f #f)
               "==================== TEST SUMMARY =========================="))
    (newline)
    (display "  Total:  ")
    (display (ctx-run))
    (display " tests")
    (newline)
    (display "  Passed: ")
    (display (colored-text (style-fg color-green) (number->string (ctx-passed))))
    (newline)
    (display "  Failed: ")
    (display (colored-text (style-fg (if (> (ctx-failed) 0) color-red color-green))
               (number->string (ctx-failed))))
    (newline)
    (newline)
    (if (= (ctx-failed) 0)
        (display (colored-text (make-style color-green #f #t #f #f #f)
                   "✓ All tests passed!"))
        (display (colored-text (make-style color-red #f #t #f #f #f)
                   "✗ Some tests failed!")))
    (newline)))

(doc 'section 'override-assertion-output)

(set! assert-equal
  (lambda (expected actual)
    (unless (equal? expected actual)
      (inc-failed!)
      (display "    ")
      (display fail-indicator)
      (display " ")
      (display (ctx-name))
      (newline)
      (display (colored-text style-dim "      Expected: "))
      (write expected)
      (newline)
      (display (colored-text style-dim "      Got:      "))
      (display (colored-text (style-fg color-yellow) (format "~s" actual)))
      (newline))))

(set! assert-true
  (lambda (expr)
    (unless (eq? #t expr)
      (inc-failed!)
      (display "    ")
      (display fail-indicator)
      (display " ")
      (display (ctx-name))
      (newline)
      (display (colored-text style-dim "      Expected: "))
      (display "#t")
      (newline)
      (display (colored-text style-dim "      Got:      "))
      (display (colored-text (style-fg color-yellow) (format "~s" expr)))
      (newline))))

(set! assert-false
  (lambda (expr)
    (unless (eq? #f expr)
      (inc-failed!)
      (display "    ")
      (display fail-indicator)
      (display " ")
      (display (ctx-name))
      (newline)
      (display (colored-text style-dim "      Expected: "))
      (display "#f")
      (newline)
      (display (colored-text style-dim "      Got:      "))
      (display (colored-text (style-fg color-yellow) (format "~s" expr)))
      (newline))))

(set! assert-error
  (lambda (thunk)
    (guard (exn [else #t])
      (thunk)
      (inc-failed!)
      (display "    ")
      (display fail-indicator)
      (display " ")
      (display (ctx-name))
      (newline)
      (display (colored-text (style-fg color-yellow)
                 "      Expected error, but none was raised"))
      (newline))))

(set! assert-ok
  (lambda (result)
    (unless (ok? result)
      (inc-failed!)
      (display "    ")
      (display fail-indicator)
      (display " ")
      (display (ctx-name))
      (newline)
      (display (colored-text style-dim "      Expected (ok ...), got: "))
      (display (colored-text (style-fg color-yellow) (format "~s" result)))
      (newline))))

(set! test
  (lambda (name expected actual)
    (set-name! name)
    (inc-run!)
    (if (equal? expected actual)
        (begin
          (inc-passed!)
          (display "  ")
          (display pass-indicator)
          (display " ")
          (display name)
          (newline))
        (begin
          (inc-failed!)
          (display "  ")
          (display fail-indicator)
          (display " ")
          (display name)
          (display (colored-text style-dim " — expected "))
          (write expected)
          (display (colored-text style-dim ", got "))
          (display (colored-text (style-fg color-yellow) (format "~s" actual)))
          (newline)))))

(doc 'section 'module-loaded-message)

(display (colored-text (style-fg color-cyan) "ANSI test output enabled."))
(newline)
