(load "core/base/prelude.ss")
(load "lattice/algebra/multivariate.ss")

(doc 'module 'groebner)
(doc 'description "Gröbner bases")
(doc 'layer 'lattice)
(doc 'purity 'total)

(doc 'note "Pure, functional implementation of Gröbner basis computation:")
(doc 'note "- Buchberger's algorithm")
(doc 'note "- S-polynomial computation")
(doc 'note "- Polynomial reduction")
(doc 'note "- Reduced Gröbner bases")
(doc 'note "- Ideal membership testing")

(doc 'note "NOTE: Requires polynomial coefficients from a Field (not just Ring)")
(doc 'note "because multivariate polynomial division requires coefficient division.")

(doc 'section 's-polynomial)

(doc 'note "The S-polynomial of f and g \"cancels\" their leading terms:")
(doc 'note "")
(doc 'note "S(f,g) = (lcm(LM(f), LM(g)) / LT(f)) * f - (lcm(LM(f), LM(g)) / LT(g)) * g")
(doc 'note "")
(doc 'note "where LT = leading term (coeff * monomial), LM = leading monomial.")
(define (s-polynomial f g)
  (doc 'export #t)
  (let* ([F (mpoly-field f)]
         [vars (mpoly-vars f)]
         [ordering (mpoly-ordering f)]
         ;; Leading terms
         [lt-f (mpoly-leading-term f)]
         [lt-g (mpoly-leading-term g)]
         [lc-f (car lt-f)]
         [lc-g (car lt-g)]
         [lm-f (cdr lt-f)]
         [lm-g (cdr lt-g)]
         ;; LCM of leading monomials
         [lcm-fg (mono-lcm lm-f lm-g)]
         ;; Quotients: lcm/lm
         [quot-f (mono-div lcm-fg lm-f)]
         [quot-g (mono-div lcm-fg lm-g)]
         ;; Scale factors to make leading terms cancel
         ;; We need (lc-g * lcm/lm-f) * f - (lc-f * lcm/lm-g) * g
         [term-f (cons lc-g quot-f)]
         [term-g (cons lc-f quot-g)])
    (mpoly-sub (mpoly-mul-term f term-f)
               (mpoly-mul-term g term-g))))

;;; ====
;;; Polynomial Reduction
;;; ====

;;; reduce-poly : MPoly × (List MPoly) → MPoly
;;; Reduce polynomial p modulo a set of polynomials G.
;;; Returns the remainder after multivariate division.
(define (reduce-poly p G)
  (doc 'export #t)
  (let ([result (mpoly-divmod p G)])
    (cdr result)))  ; Return remainder

;;; reduce-poly-full : MPoly × (List MPoly) → MPoly
;;; Fully reduce polynomial (reduce until no change).
(define (reduce-poly-full p G)
  (doc 'export #t)
  (let loop ([current p])
    (let ([reduced (reduce-poly current G)])
      (if (mpoly-equal? reduced current)
          reduced
          (loop reduced)))))

;;; ====
;;; Buchberger's Algorithm
;;; ====

;;; buchberger : (List MPoly) → (List MPoly)
;;; Compute a Gröbner basis for the ideal generated by F.
;;; Uses basic Buchberger algorithm with pair elimination criteria.
(define (buchberger F)
  (doc 'export #t)
  (if (null? F)
      '()
      (let ([Fld (mpoly-field (car F))]
            [vars (mpoly-vars (car F))]
            [ordering (mpoly-ordering (car F))])
        ;; Initialize with non-zero input polynomials
        (let ([G (filter (lambda (f) (not (mpoly-zero? f))) F)])
          (if (null? G)
              (list (mpoly-zero Fld vars ordering))
              (buchberger-loop G (all-pairs (length G)) Fld vars ordering))))))

;;; buchberger-loop : main loop of Buchberger's algorithm
(define (buchberger-loop G pairs Fld vars ordering)
  (if (null? pairs)
      G
      (let* ([pair (car pairs)]
             [i (car pair)]
             [j (cdr pair)]
             [fi (list-ref G i)]
             [fj (list-ref G j)])
        ;; Check Buchberger criteria for pair elimination
        (if (buchberger-criterion-1? fi fj)
            ;; Skip this pair (leading monomials coprime)
            (buchberger-loop G (cdr pairs) Fld vars ordering)
            ;; Compute S-polynomial and reduce
            (let* ([s (s-polynomial fi fj)]
                   [r (reduce-poly s G)])
              (if (mpoly-zero? r)
                  ;; S-poly reduces to zero, continue
                  (buchberger-loop G (cdr pairs) Fld vars ordering)
                  ;; Non-zero remainder: add to basis
                  (let* ([new-idx (length G)]
                         [new-G (append G (list r))]
                         ;; Add new pairs with the new element
                         [new-pairs (append (cdr pairs)
                                           (map (lambda (k) (cons k new-idx))
                                                (range 0 new-idx)))])
                    (buchberger-loop new-G new-pairs Fld vars ordering))))))))

;;; buchberger-criterion-1? : MPoly × MPoly → Boolean
;;; First Buchberger criterion: if LM(f) and LM(g) are coprime,
;;; then S(f,g) reduces to zero.
(define (buchberger-criterion-1? f g)
  (let ([lm-f (mpoly-leading-mono f)]
        [lm-g (mpoly-leading-mono g)])
    ;; Coprime means GCD = 1 (empty monomial)
    (null? (mono-gcd lm-f lm-g))))

;;; all-pairs : Nat → (List (Nat × Nat))
;;; Generate all pairs (i,j) with 0 ≤ i < j < n.
(define (all-pairs n)
  (let outer ([i 0] [result '()])
    (if (>= i (- n 1))
        (reverse result)
        (let inner ([j (+ i 1)] [acc result])
          (if (>= j n)
              (outer (+ i 1) acc)
              (inner (+ j 1) (cons (cons i j) acc)))))))

;;; range provided by prelude

;;; ====
;;; Reduced Gröbner Basis
;;; ====

;;; A Gröbner basis is reduced if:
;;; 1. Each polynomial is monic (leading coefficient = 1)
;;; 2. No monomial of any polynomial is divisible by the
;;;    leading monomial of another polynomial in the basis

;;; reduce-basis : (List MPoly) → (List MPoly)
;;; Convert Gröbner basis to reduced form.
(define (reduce-basis G)
  (doc 'export #t)
  (if (null? G)
      '()
      (let* ([Fld (mpoly-field (car G))]
             ;; Make all polynomials monic
             [monic-G (map (lambda (p) (mpoly-make-monic p Fld)) G)]
             ;; Remove redundant elements
             [minimal (minimize-basis monic-G)]
             ;; Interreduce
             [reduced (interreduce minimal Fld)])
        reduced)))

;;; mpoly-make-monic : MPoly × Field → MPoly
;;; Scale polynomial so leading coefficient is 1.
(define (mpoly-make-monic p F)
  (doc 'export #t)
  (if (mpoly-zero? p)
      p
      (let* ([lc (mpoly-leading-coeff p)]
             [inv-lc (field-inv F lc)])
        (mpoly-scale p inv-lc))))

;;; minimize-basis : (List MPoly) → (List MPoly)
;;; Remove elements whose leading monomials are divisible by others.
(define (minimize-basis G)
  (doc 'export #t)
  (filter (lambda (g)
            (not (any-divides-lm? g (remove-equal g G mpoly-equal?))))
          G))

;;; any-divides-lm? : MPoly × (List MPoly) → Boolean
;;; Does any element of G divide the leading monomial of p?
(define (any-divides-lm? p G)
  (let ([lm-p (mpoly-leading-mono p)])
    (any (lambda (g)
           (mono-divides? (mpoly-leading-mono g) lm-p))
         G)))

;;; interreduce : (List MPoly) × Field → (List MPoly)
;;; Reduce each polynomial modulo the others.
(define (interreduce G Fld)
  (doc 'export #t)
  (let loop ([remaining G] [done '()])
    (if (null? remaining)
        (reverse done)
        (let* ([p (car remaining)]
               [others (append (cdr remaining) done)]
               [reduced (if (null? others)
                           p
                           (reduce-poly-full p others))])
          (loop (cdr remaining)
                (cons (mpoly-make-monic reduced Fld) done))))))

;;; remove-equal : α × (List α) × (α×α→Bool) → (List α)
(define (remove-equal x lst eq-fn)
  (filter (lambda (y) (not (eq-fn x y))) lst))

;;; any : (α → Bool) × (List α) → Bool
(define (any pred lst)
  (cond
    [(null? lst) #f]
    [(pred (car lst)) #t]
    [else (any pred (cdr lst))]))

;;; ====
;;; Gröbner Basis Applications
;;; ====

;;; ideal-membership? : MPoly × (List MPoly) → Boolean
;;; Test if polynomial f is in the ideal generated by G.
;;; G should be a Gröbner basis.
(define (ideal-membership? f G)
  (doc 'export #t)
  (let ([r (reduce-poly f G)])
    (mpoly-zero? r)))

;;; solve-system : (List MPoly) → (List MPoly)
;;; Solve polynomial system by computing reduced Gröbner basis
;;; with grevlex ordering (typically good for solving).
;;; Returns reduced Gröbner basis.
(define (solve-system polys)
  (doc 'export #t)
  (reduce-basis (buchberger polys)))

;;; ideal-intersection : (List MPoly) × (List MPoly) → (List MPoly)
;;; Compute generators for intersection of two ideals.
;;; Uses the elimination technique: I ∩ J = (tI + (1-t)J) ∩ R[x1,...,xn]
;;; Note: This requires introducing a new variable and elimination ordering.
(define (ideal-intersection I J)
  ;; For now, return placeholder - full implementation requires
  ;; variable management and elimination orderings
  (error 'ideal-intersection "not yet implemented - requires elimination"))

;;; ideal-quotient : (List MPoly) × MPoly → (List MPoly)
;;; Compute the ideal quotient I:f = {g | g*f ∈ I}.
;;; Note: Requires saturation computation.
(define (ideal-quotient I f)
  (error 'ideal-quotient "not yet implemented - requires saturation"))

;;; ====
;;; Normal Form
;;; ====

;;; normal-form : MPoly × (List MPoly) → MPoly
;;; Compute the normal form of f with respect to Gröbner basis G.
;;; This is the unique remainder modulo G.
(define (normal-form f G)
  (doc 'export #t)
  (reduce-poly-full f G))

;;; ====
;;; Basis Verification
;;; ====

;;; is-groebner-basis? : (List MPoly) → Boolean
;;; Verify that G is a Gröbner basis (all S-polys reduce to zero).
(define (is-groebner-basis? G)
  (doc 'export #t)
  (let ([n (length G)]
        [pairs (all-pairs (length G))])
    (let loop ([ps pairs])
      (if (null? ps)
          #t
          (let* ([pair (car ps)]
                 [fi (list-ref G (car pair))]
                 [fj (list-ref G (cdr pair))]
                 [s (s-polynomial fi fj)]
                 [r (reduce-poly s G)])
            (if (mpoly-zero? r)
                (loop (cdr ps))
                #f))))))

;;; ====
;;; Display
;;; ====

;;; groebner->string : (List MPoly) → String
;;; Pretty-print Gröbner basis.
(define (groebner->string G)
  (doc 'export #t)
  (string-append
   "Gröbner basis with " (number->string (length G)) " elements:\n"
   (string-join (map (lambda (g) (string-append "  " (mpoly->string g)))
                     G)
                "\n")))

;;; string-join defined in multivariate.ss
